### PR TITLE
fix: typo in cmakeListsPath for turbo native modules

### LINKED ISSUE #627: Unable to run android starter
### Description

```
npx create-react-native-library@latest RTNMute3

❯   Turbo module - requires new arch (experimental)
❯   Kotlin & Objective-C
❯   Test app - app's native code is abstracted away

cd RTNMute3
nvm use 
yarn
yarn example start
yarn example android
```

Yields the following error

```
[CXX1429] error when building with cmake using /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/src/main/jni/CMakeLists.txt: -- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/arm64-v8a/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    /Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/src/main/jni \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=23 \
      -DANDROID_PLATFORM=android-23 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_ANDROID_NDK=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      "-DCMAKE_CXX_FLAGS=-std=c++20 -frtti -fexceptions -DWITH_INSPECTOR=1" \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/intermediates/cxx/Debug/5l6s374r/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/intermediates/cxx/Debug/5l6s374r/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_FIND_ROOT_PATH=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/prefab/arm64-v8a/prefab \
      -B/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/arm64-v8a \
      -GNinja \
      -DANDROID_STL=c++_shared \
      -DNODE_MODULES_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/.. \
      -DPROJECT_BUILD_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build \
      -DREACT_ANDROID_BUILD_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/build \
      -DREACT_ANDROID_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid \
      -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=ON
  from /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app
CMake Error at /Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:5 (add_subdirectory):
  add_subdirectory given source
  "/Users/christopherpitt/Development/luna/RTNMute3/android/generated/jni/"
  which is not an existing directory.
Call Stack (most recent call first):
  /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:135 (include)
  CMakeLists.txt:23 (include)


CMake Error at /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:138 (target_link_libraries):
  Cannot specify link libraries for target "react_codegen_RNRTNMuteSpec"
  which is not built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include) : com.android.ide.common.process.ProcessException: -- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/arm64-v8a/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    /Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/src/main/jni \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=23 \
      -DANDROID_PLATFORM=android-23 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_ANDROID_NDK=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      "-DCMAKE_CXX_FLAGS=-std=c++20 -frtti -fexceptions -DWITH_INSPECTOR=1" \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/intermediates/cxx/Debug/5l6s374r/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/intermediates/cxx/Debug/5l6s374r/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_FIND_ROOT_PATH=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/prefab/arm64-v8a/prefab \
      -B/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/arm64-v8a \
      -GNinja \
      -DANDROID_STL=c++_shared \
      -DNODE_MODULES_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/.. \
      -DPROJECT_BUILD_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build \
      -DREACT_ANDROID_BUILD_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/build \
      -DREACT_ANDROID_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid \
      -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=ON
  from /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app
CMake Error at /Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:5 (add_subdirectory):
  add_subdirectory given source
  "/Users/christopherpitt/Development/luna/RTNMute3/android/generated/jni/"
  which is not an existing directory.
Call Stack (most recent call first):
  /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:135 (include)
  CMakeLists.txt:23 (include)


CMake Error at /Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:138 (target_link_libraries):
  Cannot specify link libraries for target "react_codegen_RNRTNMuteSpec"
  which is not built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:288)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:108)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:106)
	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess(ExecuteProcess.kt:106)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess$default(ExecuteProcess.kt:85)
	at com.android.build.gradle.tasks.CmakeQueryMetadataGenerator.executeProcess(CmakeFileApiMetadataGenerator.kt:59)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:247)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:247)
	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configureOneAbi(ExternalNativeJsonGenerator.kt:247)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configure(ExternalNativeJsonGenerator.kt:113)
	at com.android.build.gradle.tasks.ExternalNativeBuildJsonTask.doTaskAction(ExternalNativeBuildJsonTask.kt:90)
	at com.android.build.gradle.internal.tasks.UnsafeOutputsTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:65)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.internal.tasks.UnsafeOutputsTask.taskAction(UnsafeOutputsTask.kt:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:229)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:212)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:195)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:162)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
	at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
	at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:67)
	at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:45)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
	at org.gradle.internal.Either$Right.fold(Either.java:175)
	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:76)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:54)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
	at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
	at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:106)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:55)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.android.ide.common.process.ProcessException: Error while executing process /Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/cmake with arguments {-H/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/src/main/jni -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=23 -DANDROID_PLATFORM=android-23 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125 -DCMAKE_ANDROID_NDK=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125 -DCMAKE_TOOLCHAIN_FILE=/Users/christopherpitt/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/ninja -DCMAKE_CXX_FLAGS=-std=c++20 -frtti -fexceptions -DWITH_INSPECTOR=1 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/intermediates/cxx/Debug/5l6s374r/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/intermediates/cxx/Debug/5l6s374r/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/prefab/arm64-v8a/prefab -B/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native-test-app/android/app/.cxx/Debug/5l6s374r/arm64-v8a -GNinja -DANDROID_STL=c++_shared -DNODE_MODULES_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/.. -DPROJECT_BUILD_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build -DREACT_ANDROID_BUILD_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid/build -DREACT_ANDROID_DIR=/Users/christopherpitt/Development/luna/RTNMute3/example/node_modules/react-native/ReactAndroid -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=ON}
	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:277)
	... 141 more
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Users/christopherpitt/Library/Android/sdk/cmake/3.22.1/bin/cmake'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:442)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
	... 142 more
```

I think it might be something to do with this file - note the space in the directory path passed to "add_subdirectory": 

/Users/christopherpitt/Development/luna/RTNMute3/example/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake
```
# This code was generated by [React Native](https://www.npmjs.com/package/@react-native/gradle-plugin)
cmake_minimum_required(VERSION 3.13)
set(CMAKE_VERBOSE_MAKEFILE on)

**add_subdirectory(/Users/christopherpitt/Development/luna/RTNMute3/android/generated/jni/ RNRTNMuteSpec_autolinked_build)**

set(AUTOLINKED_LIBRARIES
  react_codegen_RNRTNMuteSpec
)
```

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

❯   Turbo module - requires new arch (experimental)

### Link to repro

https://github.com/72days/TestNewFabricModule

### Environment

System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Pro
  Memory: 144.70 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

### PR DESCRIPTION
**Pull request by withSang**
### Summary

It fixes #627, as we were having the same issue in our react native project.
When opting in Turbo Native Modules or Fabric Views, `cmakeListPath` in generated `react-native.config.js` was not consistent with the hierarchy generated by CodeGen.
This fix corrects the path as stated by document.

If my fix isn't correct, feel free to correct me.
Thank you.

### Test plan

- Select 'Turbo module - requires new arch (experimental)' to create Turbo native module and include it into the project
- Build for android with `npx react-native run-android` to validate the fix was correct.

### CODE REVIEW

**Comment by withSang** [comment]
In the issue #627,  It seems `cmakeListsPath` should be adjusted from `generated/jni/CMakeLists.txt` to `build/generated/source/codegen/jni/CMakeLists.txt` only when it is a local library.

I tried to correct that by editing the template.

**Comment by withSang** [comment]
Oh, I see I've made formatting error. I've fixed it again. Sorry.

File: packages/create-react-native-library/src/index.ts [hunk 1]
```diff
@@ -657,6 +657,7 @@ async function create(_argv: yargs.Arguments<any>) {
     repo: repoUrl,
     example,
     year: new Date().getFullYear(),
+    local,
```
Comment (atlj) [inline packages/create-react-native-library/src/index.ts:660]:
```suggestion
```
We don't need to add a new property here, we can use `example === 'local'` instead.

File: packages/create-react-native-library/templates/native-library-mixed/react-native.config.js [hunk 2]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <%_ if (local) { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <%_ } else { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <%_ } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-library-mixed/react-native.config.js:12]:
```suggestion
        <% if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <% } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <% } -%>
```
Let's swap the order so we also cover the test app.

File: packages/create-react-native-library/templates/native-library-new/react-native.config.js [hunk 3]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <%_ if (local) { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <%_ } else { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <%_ } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-library-new/react-native.config.js:12]:
```suggestion
        <% if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <% } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <% } -%>
```
Let's swap the order so we also cover the test app.

File: packages/create-react-native-library/templates/native-view-mixed/react-native.config.js [hunk 4]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <%_ if (local) { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <%_ } else { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <%_ } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-view-mixed/react-native.config.js:12]:
```suggestion
        <% if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <% } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <% } -%>
```
Let's swap the order so we also cover the test app.

File: packages/create-react-native-library/templates/native-view-new/react-native.config.js [hunk 5]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <%_ if (local) { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <%_ } else { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <%_ } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-view-new/react-native.config.js:12]:
```suggestion
        <% if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <% } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <% } -%>
```
Let's swap the order so we also cover the test app.

**Review by atlj — CHANGES_REQUESTED** [review]

**Comment by atlj** [comment]
Thanks a ton for sending this! I totally passed the fact we have a local template option. I've made some changes, let's see if CI passes and we can merge this!

File: packages/create-react-native-library/templates/native-library-mixed/react-native.config.js [hunk 6]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <% if (example === 'vanilla') { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <% } else { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <% } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-library-mixed/react-native.config.js:12]:
```suggestion
        <%_ if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <%_ } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <%_ } -%>
```

File: packages/create-react-native-library/templates/native-library-new/react-native.config.js [hunk 7]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <% if (example === 'vanilla') { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <% } else { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <% } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-library-new/react-native.config.js:12]:
```suggestion
        <%_ if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <%_ } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <%_ } -%>
```

File: packages/create-react-native-library/templates/native-view-mixed/react-native.config.js [hunk 8]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <% if (example === 'vanilla') { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <% } else { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <% } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-view-mixed/react-native.config.js:12]:
```suggestion
        <%_ if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <%_ } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <%_ } -%>
```

File: packages/create-react-native-library/templates/native-view-new/react-native.config.js [hunk 9]
```diff
@@ -5,7 +5,11 @@ module.exports = {
   dependency: {
     platforms: {
       android: {
+        <% if (example === 'vanilla') { -%>
         cmakeListsPath: 'generated/jni/CMakeLists.txt',
+        <% } else { -%>
+        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
+        <% } -%>
```
Comment (atlj) [inline packages/create-react-native-library/templates/native-view-new/react-native.config.js:12]:
```suggestion
        <%_ if (example === 'vanilla') { -%>
        cmakeListsPath: 'generated/jni/CMakeLists.txt',
        <%_ } else { -%>
        cmakeListsPath: 'build/generated/source/codegen/jni/CMakeLists.txt',
        <%_ } -%>
```

**Review by atlj — APPROVED** [review]

**Comment by atlj** [comment]
Looks like some options fails but this only happens on CI, some specific templates, and looks like this is a known problem in community CLI https://github.com/react-native-community/cli/issues/2498. So this should be good to merge.

**Comment by withSang** [comment]
Thank you a lot!! Hope you have a nice day! 👍
